baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Call Detective'

ignoreLogs = ['warning-goldmark-raw-html']

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Verify'
pageRef = '/verify'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  [params.style]
    ThemeColor = '#CB7E30'
    xsmallBreakPoint = '425px'
    smallBreakPoint = '768px'
    mediumBreakPoint = '1024px'
    largeBreakPoint = '1200px'
