baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Call Detective'

[[server.headers]]
for = "/**"

[server.headers.values]
Access-Control-Allow-Origin = "*"
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"

ignoreLogs = ['warning-goldmark-raw-html']

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 10

[params]
  [params.style]
    ThemeColor = '#CB7E30'
    xsmallBreakPoint = '425px'
    smallBreakPoint = '768px'
    mediumBreakPoint = '1024px'
    largeBreakPoint = '1200px'
    ThemeColorHsl = '30deg, 62%, 49%'
    [params.style.ThemeShades]
    # https://codepen.io/claviska/pen/QWveRgL
      50 = '252 249 245'
      100 = '247 234 222'
      200 = '240 219 196'
      300 = '233 201 168'
      400 = '224 177 130'
      500 = '211 146 80'
      600 = '186 115 44'
      700 = '153 95 36'
      800 = '126 78 30'
      900 = '90 56 21'
      950 = '55 34 13'
